/**
 * @note cat weather-icons-react/index.js | grep "export const" | sed 's/const /class /g' | sed 's/= function (props) {/extends React.Component {}/g
 * @see https://najens.github.io/weather-icons-react/
 */
declare module "weather-icons-react" {
  export class WiAlien extends React.Component {}
  export class WiBarometer extends React.Component {}
  export class WiCelsius extends React.Component {}
  export class WiCloudDown extends React.Component {}
  export class WiCloudRefresh extends React.Component {}
  export class WiCloudUp extends React.Component {}
  export class WiCloud extends React.Component {}
  export class WiCloudyGusts extends React.Component {}
  export class WiCloudyWindy extends React.Component {}
  export class WiCloudy extends React.Component {}
  export class WiDayCloudyGusts extends React.Component {}
  export class WiDayCloudyHigh extends React.Component {}
  export class WiDayCloudyWindy extends React.Component {}
  export class WiDayCloudy extends React.Component {}
  export class WiDayFog extends React.Component {}
  export class WiDayHail extends React.Component {}
  export class WiDayHaze extends React.Component {}
  export class WiDayLightWind extends React.Component {}
  export class WiDayLightning extends React.Component {}
  export class WiDayRainMix extends React.Component {}
  export class WiDayRainWind extends React.Component {}
  export class WiDayRain extends React.Component {}
  export class WiDayShowers extends React.Component {}
  export class WiDaySleetStorm extends React.Component {}
  export class WiDaySleet extends React.Component {}
  export class WiDaySnowThunderstorm extends React.Component {}
  export class WiDaySnowWind extends React.Component {}
  export class WiDaySnow extends React.Component {}
  export class WiDaySprinkle extends React.Component {}
  export class WiDayStormShowers extends React.Component {}
  export class WiDaySunnyOvercast extends React.Component {}
  export class WiDaySunny extends React.Component {}
  export class WiDayThunderstorm extends React.Component {}
  export class WiDayWindy extends React.Component {}
  export class WiDegrees extends React.Component {}
  export class WiDirectionDownLeft extends React.Component {}
  export class WiDirectionDownRight extends React.Component {}
  export class WiDirectionDown extends React.Component {}
  export class WiDirectionLeft extends React.Component {}
  export class WiDirectionRight extends React.Component {}
  export class WiDirectionUpLeft extends React.Component {}
  export class WiDirectionUpRight extends React.Component {}
  export class WiDirectionUp extends React.Component {}
  export class WiDust extends React.Component {}
  export class WiEarthquake extends React.Component {}
  export class WiFahrenheit extends React.Component {}
  export class WiFire extends React.Component {}
  export class WiFlood extends React.Component {}
  export class WiFog extends React.Component {}
  export class WiGaleWarning extends React.Component {}
  export class WiHail extends React.Component {}
  export class WiHorizonAlt extends React.Component {}
  export class WiHorizon extends React.Component {}
  export class WiHot extends React.Component {}
  export class WiHumidity extends React.Component {}
  export class WiHurricaneWarning extends React.Component {}
  export class WiHurricane extends React.Component {}
  export class WiLightning extends React.Component {}
  export class WiLunarEclipse extends React.Component {}
  export class WiMeteor extends React.Component {}
  export class WiMoonAltFirstQuarter extends React.Component {}
  export class WiMoonAltFull extends React.Component {}
  export class WiMoonAltNew extends React.Component {}
  export class WiMoonAltThirdQuarter extends React.Component {}
  export class WiMoonAltWaningCrescent1 extends React.Component {}
  export class WiMoonAltWaningCrescent2 extends React.Component {}
  export class WiMoonAltWaningCrescent3 extends React.Component {}
  export class WiMoonAltWaningCrescent4 extends React.Component {}
  export class WiMoonAltWaningCrescent5 extends React.Component {}
  export class WiMoonAltWaningCrescent6 extends React.Component {}
  export class WiMoonAltWaningGibbous1 extends React.Component {}
  export class WiMoonAltWaningGibbous2 extends React.Component {}
  export class WiMoonAltWaningGibbous3 extends React.Component {}
  export class WiMoonAltWaningGibbous4 extends React.Component {}
  export class WiMoonAltWaningGibbous5 extends React.Component {}
  export class WiMoonAltWaningGibbous6 extends React.Component {}
  export class WiMoonAltWaxingCrescent1 extends React.Component {}
  export class WiMoonAltWaxingCrescent2 extends React.Component {}
  export class WiMoonAltWaxingCrescent3 extends React.Component {}
  export class WiMoonAltWaxingCrescent4 extends React.Component {}
  export class WiMoonAltWaxingCrescent5 extends React.Component {}
  export class WiMoonAltWaxingCrescent6 extends React.Component {}
  export class WiMoonAltWaxingGibbous1 extends React.Component {}
  export class WiMoonAltWaxingGibbous2 extends React.Component {}
  export class WiMoonAltWaxingGibbous3 extends React.Component {}
  export class WiMoonAltWaxingGibbous4 extends React.Component {}
  export class WiMoonAltWaxingGibbous5 extends React.Component {}
  export class WiMoonAltWaxingGibbous6 extends React.Component {}
  export class WiMoonFirstQuarter extends React.Component {}
  export class WiMoonFull extends React.Component {}
  export class WiMoonNew extends React.Component {}
  export class WiMoonThirdQuarter extends React.Component {}
  export class WiMoonWaningCrescent1 extends React.Component {}
  export class WiMoonWaningCrescent2 extends React.Component {}
  export class WiMoonWaningCrescent3 extends React.Component {}
  export class WiMoonWaningCrescent4 extends React.Component {}
  export class WiMoonWaningCrescent5 extends React.Component {}
  export class WiMoonWaningCrescent6 extends React.Component {}
  export class WiMoonWaningGibbous1 extends React.Component {}
  export class WiMoonWaningGibbous2 extends React.Component {}
  export class WiMoonWaningGibbous3 extends React.Component {}
  export class WiMoonWaningGibbous4 extends React.Component {}
  export class WiMoonWaningGibbous5 extends React.Component {}
  export class WiMoonWaningGibbous6 extends React.Component {}
  export class WiMoonWaxingCrescent1 extends React.Component {}
  export class WiMoonWaxingCrescent2 extends React.Component {}
  export class WiMoonWaxingCrescent3 extends React.Component {}
  export class WiMoonWaxingCrescent4 extends React.Component {}
  export class WiMoonWaxingCrescent5 extends React.Component {}
  export class WiMoonWaxingCrescent6 extends React.Component {}
  export class WiMoonWaxingGibbous1 extends React.Component {}
  export class WiMoonWaxingGibbous2 extends React.Component {}
  export class WiMoonWaxingGibbous3 extends React.Component {}
  export class WiMoonWaxingGibbous4 extends React.Component {}
  export class WiMoonWaxingGibbous5 extends React.Component {}
  export class WiMoonWaxingGibbous6 extends React.Component {}
  export class WiMoonrise extends React.Component {}
  export class WiMoonset extends React.Component {}
  export class WiNA extends React.Component {}
  export class WiNightAltCloudyGusts extends React.Component {}
  export class WiNightAltCloudyHigh extends React.Component {}
  export class WiNightAltCloudyWindy extends React.Component {}
  export class WiNightAltCloudy extends React.Component {}
  export class WiNightAltHail extends React.Component {}
  export class WiNightAltLightning extends React.Component {}
  export class WiNightAltPartlyCloudy extends React.Component {}
  export class WiNightAltRainMix extends React.Component {}
  export class WiNightAltRainWind extends React.Component {}
  export class WiNightAltRain extends React.Component {}
  export class WiNightAltShowers extends React.Component {}
  export class WiNightAltSleetStorm extends React.Component {}
  export class WiNightAltSleet extends React.Component {}
  export class WiNightAltSnowThunderstorm extends React.Component {}
  export class WiNightAltSnowWind extends React.Component {}
  export class WiNightAltSnow extends React.Component {}
  export class WiNightAltSprinkle extends React.Component {}
  export class WiNightAltStormShowers extends React.Component {}
  export class WiNightAltThunderstorm extends React.Component {}
  export class WiNightClear extends React.Component {}
  export class WiNightCloudyGusts extends React.Component {}
  export class WiNightCloudyHigh extends React.Component {}
  export class WiNightCloudyWindy extends React.Component {}
  export class WiNightCloudy extends React.Component {}
  export class WiNightFog extends React.Component {}
  export class WiNightHail extends React.Component {}
  export class WiNightLightning extends React.Component {}
  export class WiNightPartlyCloudy extends React.Component {}
  export class WiNightRainMix extends React.Component {}
  export class WiNightRainWind extends React.Component {}
  export class WiNightRain extends React.Component {}
  export class WiNightShowers extends React.Component {}
  export class WiNightSleetStorm extends React.Component {}
  export class WiNightSleet extends React.Component {}
  export class WiNightSnowThunderstorm extends React.Component {}
  export class WiNightSnowWind extends React.Component {}
  export class WiNightSnow extends React.Component {}
  export class WiNightSprinkle extends React.Component {}
  export class WiNightStormShowers extends React.Component {}
  export class WiNightThunderstorm extends React.Component {}
  export class WiRainMix extends React.Component {}
  export class WiRainWind extends React.Component {}
  export class WiRain extends React.Component {}
  export class WiRaindrop extends React.Component {}
  export class WiRaindrops extends React.Component {}
  export class WiRefreshAlt extends React.Component {}
  export class WiRefresh extends React.Component {}
  export class WiSandstorm extends React.Component {}
  export class WiShowers extends React.Component {}
  export class WiSleet extends React.Component {}
  export class WiSmallCraftAdvisory extends React.Component {}
  export class WiSmog extends React.Component {}
  export class WiSmoke extends React.Component {}
  export class WiSnowWind extends React.Component {}
  export class WiSnow extends React.Component {}
  export class WiSnowflakeCold extends React.Component {}
  export class WiSolarEclipse extends React.Component {}
  export class WiSprinkle extends React.Component {}
  export class WiStars extends React.Component {}
  export class WiStormShowers extends React.Component {}
  export class WiStormWarning extends React.Component {}
  export class WiStrongWind extends React.Component {}
  export class WiSunrise extends React.Component {}
  export class WiSunset extends React.Component {}
  export class WiThermometerExterior extends React.Component {}
  export class WiThermometerInternal extends React.Component {}
  export class WiThermometer extends React.Component {}
  export class WiThunderstorm extends React.Component {}
  export class WiTime1 extends React.Component {}
  export class WiTime10 extends React.Component {}
  export class WiTime11 extends React.Component {}
  export class WiTime12 extends React.Component {}
  export class WiTime2 extends React.Component {}
  export class WiTime3 extends React.Component {}
  export class WiTime4 extends React.Component {}
  export class WiTime5 extends React.Component {}
  export class WiTime6 extends React.Component {}
  export class WiTime7 extends React.Component {}
  export class WiTime8 extends React.Component {}
  export class WiTime9 extends React.Component {}
  export class WiTornado extends React.Component {}
  export class WiTrain extends React.Component {}
  export class WiTsunami extends React.Component {}
  export class WiUmbrella extends React.Component {}
  export class WiVolcano extends React.Component {}
  export class WiWindBeaufort0 extends React.Component {}
  export class WiWindBeaufort1 extends React.Component {}
  export class WiWindBeaufort10 extends React.Component {}
  export class WiWindBeaufort11 extends React.Component {}
  export class WiWindBeaufort12 extends React.Component {}
  export class WiWindBeaufort2 extends React.Component {}
  export class WiWindBeaufort3 extends React.Component {}
  export class WiWindBeaufort4 extends React.Component {}
  export class WiWindBeaufort5 extends React.Component {}
  export class WiWindBeaufort6 extends React.Component {}
  export class WiWindBeaufort7 extends React.Component {}
  export class WiWindBeaufort8 extends React.Component {}
  export class WiWindBeaufort9 extends React.Component {}
  export class WiWindDeg extends React.Component {}
  export class WiWindy extends React.Component {}
}
